#!/system/bin/sh
#
############################
#Edited By: TrevE @ xda for damagedrom
#Create Log File
############################
export LOG_FILE=/cache/dcboot.log
if [ -e $LOG_FILE ]; then
  	rm $LOG_FILE;
fi;

echo "Starting DamageControl BootScript at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE;