#!/system/bin/sh.old
# Give us props if you use any of our stuff
# follow good open source etiquette
# thanks from Team Synergy
# 
#######################
#Setting up File System
#######################
export androidversion=`getprop ro.build.version.release`;
export rosecure=`getprop ro.secure`;
SYNERGYROM=1;
busybox mount -o remount,rw -t auto /data;
export LOG_FILE=/cache/dcboot.log;
echo "[ ] Mounting system.  Check number 1 your properly rooted..." | tee -a $LOG_FILE;
busybox mount -o remount,rw -t auto /system;
if [ $? != 0 ];
	then
		echo "[!!] Check your NAND Unlocked.  Cannot mount system as RW!!!!!!!! Disabling Most features...." | tee -a $LOG_FILE;
		setprop dc.a2sd.active false;
		setprop dc.swap.active false;
		setprop dc.wirelessn.active false;
		setprop dc.bannedapp.active false;
		setprop dc.firstboot.active false;
		setprop dc.zipalign.active false;
		setprop dc.jit.active false;

fi;

echo "[ ] Check number 2 - Testing if you are NAND unlocked..." | tee -a $LOG_FILE;
echo DCRomWriteTest >/system/etc/dcromtest.test;
if [ ! -e /system/etc/dcromtest.test ];
then
	echo "[!!] Check your NAND Unlocked.  Cannot write to system!!!!!!!! Disabling Most features...." | tee -a $LOG_FILE;
		setprop dc.a2sd.active false;
		setprop dc.swap.active false;
		setprop dc.wirelessn.active false;
		setprop dc.bannedapp.active false;
		setprop dc.firstboot.active false;
		setprop dc.zipalign.active false;
		setprop dc.jit.active false;

fi;

echo "[ ] Check number 3 - Testing if ro.secure is 0..." | tee -a $LOG_FILE;
if [ -n $rosecure ] && [ $rosecure = "1" ];
then
	echo "[!!] Check your Kernel!  ro.secure is set to 1! Disabling Most features...." | tee -a $LOG_FILE;
		setprop dc.a2sd.active false;
		setprop dc.swap.active false;
		setprop dc.wirelessn.active false;
		setprop dc.bannedapp.active false;
		setprop dc.firstboot.active false;
		setprop dc.zipalign.active false;
		setprop dc.jit.active false;

fi;	

echo "[ ] Check number 4 - Busybox..." | tee -a $LOG_FILE;
if [ ! -e /system/xbin/busybox ] && [ ! -e /system/bin/busybox ];
then
	echo "[!!] No busybox! Disabling Most features...." | tee -a $LOG_FILE;
		setprop dc.a2sd.active false;
		setprop dc.swap.active false;
		setprop dc.wirelessn.active false;
		setprop dc.bannedapp.active false;
		setprop dc.firstboot.active false;
		setprop dc.zipalign.active false;
		setprop dc.jit.active false;

fi;

echo "[ ] End root checks";
busybox rm /system/etc/dcromtest.test;

echo "[ ] Searching for Mount Point..." | tee -a $LOG_FILE;
if [ -d /system/sd ];
then
	echo "[ ] Mount point found..no further action required." | tee -a $LOG_FILE;
else
	echo "[!] Creating Mount point." | tee -a $LOG_FILE;
	busybox mkdir /system/sd;
	busybox chmod 777 /system/sd;
	echo "[ ] Mount point created." | tee -a $LOG_FILE;
fi;

