#!/system/bin/sh.old
# Give us props if you use any of our stuff
# follow good open source etiquette
# thanks from Team Synergy
# 
SYNERGYROM=1;
export LOG_FILE=/cache/dcboot.log;
export zipalign=`getprop dc.zipalign.active`;
if [ -n $zipalign ] && [ $zipalign = "true" ]; 
then
	busybox mount -o remount,rw /;
	busybox mount -o remount,rw -t auto /system;
	busybox mount -o remount,rw -t auto /data;
	
	if [ -e /mnt/tmp ];
	then
		rm -r /mnt/tmp/*;
	fi;
	else
		mkdir /mnt/tmp/;
	fi;
	busybox mount -t tmpfs -o size=70m none /mnt/tmp; 
	echo "Starting Synergy Automatic ZipAlign "  `date` | tee -a $LOG_FILE;

    for apk in /data/app/*.apk ; do
        zipalign -c 4 $apk;
        ZIPCHECK=$?;
        if [ $ZIPCHECK -eq 1 ]; then
                echo ZipAligning "$basename $apk"  | tee -a $LOG_FILE;
                zipalign -f 4 "$apk" /mnt/tmp/"$basename $apk";
                        if [ -e /mnt/tmp/"$basename $apk" ]; then
                                cp -f -p /mnt/tmp/"$basename $apk" $apk  | tee -a $LOG_FILE;
                                rm /mnt/tmp/"$basename $apk";
                        else
                                echo ZipAligning "$basename $apk" Failed SR | tee -a $LOG_FILE;
                        fi;
        else
                echo Synergy ZipAlign already completed on "$apk"  | tee -a $LOG_FILE;
        fi;
       done;
	   
	   
	for apk in /data/app_s/*.apk ; do
        zipalign -c 4 $apk;
        ZIPCHECK=$?;
        if [ $ZIPCHECK -eq 1 ]; then
                echo ZipAligning "$basename $apk"  | tee -a $LOG_FILE;
                zipalign -f 4 $apk /mnt/tmp/"$basename $apk";
                        if [ -e /mnt/tmp/"$basename $apk" ]; then
                                cp -f -p /mnt/tmp/"$basename $apk" $apk  | tee -a $LOG_FILE;
                                rm /mnt/tmp/$basename $apk;
                        else
                                echo ZipAligning "$basename $apk" Failed SR | tee -a $LOG_FILE;
                        fi;
        else
                echo Synergy ZipAlign already completed on "$apk"  | tee -a $LOG_FILE;
        fi;
    done;

    for apk in /system/app/*.apk ; do
        zipalign -c 4 $apk;
        ZIPCHECK=$?;
        if [ $ZIPCHECK -eq 1 ]; then
                echo ZipAligning $basename $apk  | tee -a $LOG_FILE;
                zipalign -f 4 $apk /mnt/tmp/"$basename $apk";
                        if [ -e /mnt/tmp/"$basename $apk" ]; then
                                cp -f -p /mnt/tmp/"$basename $apk" $apk  | tee -a $LOG_FILE;
                                rm /mnt/tmp/"$basename $apk";
                        else
                                echo ZipAligning "$basename $apk" Failed SR | tee -a $LOG_FILE;
                        fi;
        else
                echo Synergy ZipAlign already completed on "$apk"  | tee -a $LOG_FILE;
        fi;
       done;   
	   
busybox umount /mnt/tmp	   
echo "Automatic ZipAlign finished at:" `date` | tee -a $LOG_FILE;
fi;
else
	echo "[X] Zipalign Check Disabled by dc.conf" | tee -a $LOG_FILE;
fi;
