#!/system/bin/sh.old
# Give us props if you use any of our stuff
# follow good open source etiquette
# thanks from Team Synergy
# 
#
#Clean outdated dalvik cache entries 
#modded by trev for synergykingdom
SYNERGYROM=1;
export LOG_FILE=/cache/dcboot.log;
export DALVIK=dalvikforsynergynotfound;
busybox mount -o remount,rw -t auto /system;
busybox mount -o remount,rw -t auto /data;
echo "Starting Synergy dalvik data cleanup" | tee -a $LOG_FILE;
echo "Checking where dalvik exists" | tee -a $LOG_FILE;
if [ -e "/data/dalvik-cache/system@framework@services.jar@classes.dex" ];
then
 export DALVIK=/data/dalvik-cache;
 echo "Dalvik found on Data" | tee -a $LOG_FILE;
fi;

if [ -e "/cache/dalvik-cache/system@framework@services.jar@classes.dex" ];
then
 export DALVIK=/cache/dalvik-cache;
 echo "Dalvik found on Cache" | tee -a $LOG_FILE;
fi;

if [ -e "/system/sd/dalvik-cache/system@framework@services.jar@classes.dex" ];
then
 export DALVIK=/system/sd/dalvik-cache;
 echo "Dalvik found on SD" | tee -a $LOG_FILE;
fi;

if [ "$DALVIK" != "dalvikforsynergynotfound" ];
then
	cd "$DALVIK"
	echo "Checking Dex entries from /data/app" | tee -a $LOG_FILE;
	for dex in data@app@*.dex 
	do
	 apk=`echo "$dex" | sed "s/data@app@//g" | sed "s/@classes.*//g"`;
	 if [ ! -e "/data/app/$apk" ];
	  then
	  echo "Outdated dex found for $dex removing..." | tee -a $LOG_FILE;
	  rm $dex;
	 fi;
	done;

	echo "Checking Dex entries from /system/app" | tee -a $LOG_FILE;
	for dex in system@app@*.dex 
	do
	 apk=`echo "$dex" | sed "s/system@app@//g" | sed "s/@classes.*//g"`;
	 if [ ! -e "/system/app/$apk" ];
	  then
	  echo "Outdated dex found for $dex removing..." | tee -a $LOG_FILE;
	  rm $dex;
	 fi;
	done;

	echo "Checking Dex entries from /system/framework" | tee -a $LOG_FILE;
	for dex in system@framework@*.dex 
	do
	 jar=`echo "$dex" | sed "s/system@framework@//g" | sed "s/@classes.*//g"`;
	 if [ ! -e "/system/framework/$jar" ];
	  then
	  echo "Outdated dex found for $dex removing..." | tee -a $LOG_FILE;
	  rm $dex;
	 fi;
	done;
else
	echo "No framework found, hopefully this is first boot. Skipping Synergy Cleanup Checks..." | tee -a $LOG_FILE;
fi;	