#!/system/bin/sh.old
# Give us props if you use any of our stuff
# follow good open source etiquette
# thanks from Team Synergy
# 
export SYNERGYROM=1;
#######################
#synergy flashhack script
#######################
export LOG_FILE=/cache/dcboot.log;
busybox mount -o remount,rw -t auto /system;
busybox mount -o remount,rw -t auto /data;
echo "Starting Synergy flash hack" | tee -a $LOG_FILE;
if [ -f /data/data/com.adobe.flashplayer/lib/libflashplayer.so ];
then
	SYNERGYFLASHSHA1SUM=`sha1sum /data/data/com.adobe.flashplayer/lib/libflashplayer.so | awk '{print $1 }'`;
	echo "Flash so has SHA1 of:"  $SYNERGYFLASHSHA1SUM | tee -a $LOG_FILE;
	
	#10.3.185.25
	if [ $SYNERGYFLASHSHA1SUM == "6f682a9c1f6cf9985861ea467b6ab1fdf4f3abe5" ];
	then
		rm -f /data/data/com.adobe.flashplayer/lib/libflashplayer.so;
		ln -s /data/sd/lib/synergyflashplayer10318525.so /data/data/com.adobe.flashplayer/lib/libflashplayer.so;
	else
		echo "Unknown flash version!" | tee -a $LOG_FILE;
	fi;
fi;
	
if [ -h /data/data/com.adobe.flashplayer/lib/libflashplayer.so ];
then
	echo "[*] Flash Hack Active" | tee -a $LOG_FILE;
fi;