#!/system/bin/sh.old
# Give us props if you use any of our stuff
# follow good open source etiquette
# thanks from Team Synergy
# 
###############################
#Starting FirstBoot Script
###############################
export LOG_FILE=/cache/dcboot.log;
export firstboot=`getprop dc.firstboot.active`;
busybox mount -o remount,rw -t auto /system;
busybox mount -o remount,rw -t auto /data;
busybox mount -o remount,rw -t auto /sdcard;

if [ -n $firstboot ] && [ $firstboot = "true" ]; 
then
	echo "[ ] Searching for FirstBoot script..." | tee -a $LOG_FILE;
	if [ -e /sdcard/firstboot.sh ];
	then
		echo "[!] FirstBoot script found...executing." | tee -a $LOG_FILE;
		logwrapper /system/bin/sh.old /sdcard/firstboot.sh;
		echo "[!] Removing FirstBoot Script." | tee -a $LOG_FILE;
		busybox rm -f /sdcard/firstboot.sh;
	fi;
	if [ -e /data/firstboot1.sh ];
	then
		busybox mv /sdcard/firstboot1.sh /sdcard/firstboot.sh;
	fi;
else
		echo "[X] Firstboot Script Disabled by dc.conf" | tee -a $LOG_FILE;
fi;
