#!/system/bin/sh
#######################
# Upgrade fixes written by trev
# Give us props if you use any of our stuff
# follow good open source etiquette
# thanks from Team Synergy
#######################
SYNERGYROM=1;
export LOG_FILE=/cache/sncleanup.log;
if [ -f /data/system/packages.xml ];
	then
	echo "Start synergy cleanup script";
	rm -f /data/system/packages.new;
	echo "Synergy is cleaning packages.xml for upgrade from whatever";
	cat /data/system/packages.xml | sed '/<shared-user\ name=\"com.google.android.apps.maps\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"com.google.uid.shared\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"android.uid.shared\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"android.uid.log\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"android.uid.system\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"android.uid.nfc\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"android.uid.phone\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"android.media\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"com.google.android.apps.books.uid.shared\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"android.uid.graphics\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"com.htc.sketchbook.uid\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"com.htc.googlereader.uid\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"com.htc.notes.uid\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"com.htc.rosie.uid.shared\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"com.htc.music.uid.shared\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"com.htc.mail.uid\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"com.htc.album.uid\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"com.htc.album.uid.shared\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"com.htc.ereader.uid.shared\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"com.htc.bg.uid.shared\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' |
	sed '/<shared-user\ name=\"com.htc.android.htcime.uid.shared\" userId=\"[0-9]*\">/,/<\/shared-user>/s/.*//' > /data/system/packages.new;
	echo "Synergy done editing packages, moving around"
	SYNERGYROM=1
	mv /data/system/packages.xml /data/system/packages.xml.old;
	rm -f /data/system/packages.xml;
	mv /data/system/packages.new /data/system/packages.xml;
else
	echo "Firstboot?";
fi;
	