#!/sbin/sh

# ===========================================================================
#  Virtuous ROM Tools (rmk)
#
#  Fri Sep 10 20:53:30 PDT 2010
# ===========================================================================


. /system/synergy/scripts/synergy-functions.sh

# Setup environment.

DATAMOUNTED=0
DATADATAMOUNTED=0

if $TEST $( $GREP -c " /data " "/proc/mounts" ) -eq 0; then
  $MOUNT /data
  DATAMOUNTED=1
fi

if $TEST $( $GREP -c " /datadata " "/proc/mounts" ) -eq 0; then
  $MOUNT /datadata
  DATADATAMOUNTED=1
fi

$TOUCH $PACKAGESXML
$CHOWN 1000.1000 $PACKAGESXML
$CHMOD 664 $PACKAGESXML

# Prepare data directories if the user wiped.

create_state_dirs

for DISABLED_APP in $($LS $SYNERGY_STATE_DIR/disabled/*.apk) ; do
  APPNAME=$($BASENAME $DISABLED_APP)

  $MV $SYSAPP_DIR/$APPNAME $SYNERGY_SYSTEM_DIR/app.disabled
done


# After a fresh ROM install, remove the installed state such that the
# init script is triggered on startup.

if $TEST -f $INSTALLED; then
  $RM $INSTALLED
fi

if $TEST $DATAMOUNTED -eq 1; then
  $UMOUNT /data
fi

if $TEST $DATADATAMOUNTED -eq 1; then
  $UMOUNT /datadata
fi
