#!/system/bin/sh.old
#
# Automatic Renice Phone
# by Wes Garner <wesgarner@gmail.com>
# for OpenEclair / SpareParts
#
# modded by treve for synergyrom
# Give us props if you use any of our stuff
# follow good open source etiquette
# thanks from Team Synergy
#
#
SYNERGYROM=1;
ARENICE=`getprop persist.service.auto.renice`;

while [ $ARENICE ]
do
		busybox renice -18 `pidof com.android.mms`;
		busybox renice -18 `pidof com.android.phone`;
		busybox renice -18 `pidof android.process.media`;
		busybox renice -18 `pidof mediaserver`;
		busybox renice -16 `pidof com.android.launcher`;
		busybox renice -16 `pidof com.android.launcher2`;
		busybox renice -16 `pidof com.htc.launcher`;
		busybox renice -16 `pidof com.htc.RosieUtility`;
		busybox renice -5 `busybox pidof com.android.browser`;
		#busybox renice -10 `pidof com.htc.music`;
		#busybox renice -10 `pidof com.android.music`;
		busybox renice 5 `pidof com.google.process.gapps`;
		busybox renice 5 `pidof com.google.android.apps.uploader`;
		SYNERGYDNSCHANGE=$((`getprop net.dnschange` + 1));
		setprop net.ppp0.dns1 8.8.8.8;
		setprop net.ppp0.dns2 8.8.4.4;
		setprop net.dns1 8.8.8.8;
		setprop net.dns2 8.8.4.4;
		setprop net.dns3 4.2.2.2;
		setprop net.rmnet0.dns1 8.8.8.8;
		setprop net.rmnet0.dns2 8.8.4.4;
		setprop net.dnschange `echo $SYNERGYDNSCHANGE`;
		sleep 500;
done;