#!/system/bin/sh.old
# Give us props if you use any of our stuff
# follow good open source etiquette
# thanks from Team Synergy
# 
#
#File system speedups
#
rm -f /cache/*.apk;
rm -f /cache/*.tmp;
rm -f /data/dalvik-cache/*.apk;
rm -f /data/dalvik-cache/*.tmp;
busybox mount -o remount,ro,noatime,nodirtime,barrier=0,nobh -t auto /system;
busybox mount -o remount,noatime,nodirtime,barrier=0,nobh -t auto /data;
busybox mount -o remount,noatime,nodirtime,barrier=0,nobh -t auto /cache;
insmod /system/lib/modules/perflock_disable.ko perflock_notifier_call_addr=0x`grep perflock_notifier_call /proc/kallsyms|cut -c1-8`;
insmod /system/lib/modules/cpufreq_powersave.ko;
insmod /system/lib/modules/tun.ko;
insmod /system/lib/modules/nls_utf8.ko;
insmod /system/lib/modules/cifs.ko;
sysctl -p;
sync;
setprop cm.filesystem.ready 1;
setprop dc.filesystem.ready 1;
setprop oxygen.filesystem.ready 1;
crond -c /data/cron;